version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: Server/WebApi/dockerfile
    ports:
      - "8000:80"
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User=sa;Password=Your_password123;
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: client/dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - webapi

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"